"""Agregar campos de evaluacion a examen_inscripciones

Revision ID: b1fa7a3cb11a
Revises: fed3f2b1ee7b
Create Date: 2026-03-06 12:27:55.918969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fa7a3cb11a'
down_revision = 'fed3f2b1ee7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen_inscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_tecnicas', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nota_actitud', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen_inscripciones', schema=None) as batch_op:
        batch_op.drop_column('nota_actitud')
        batch_op.drop_column('nota_tecnicas')

    # ### end Alembic commands ###
