"""init schema

Revision ID: c77ea32f331f
Revises: 
Create Date: 2026-03-03 08:28:31.033284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77ea32f331f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('datos_antes', sa.JSON(), nullable=True),
    sa.Column('datos_despues', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_academia_id'), ['academia_id'], unique=False)

    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_academia_id'), ['academia_id'], unique=False)

    op.create_table('categorias_competencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=10), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('edad_min', sa.Integer(), nullable=False),
    sa.Column('edad_max', sa.Integer(), nullable=False),
    sa.Column('peso_min', sa.Float(), nullable=True),
    sa.Column('peso_max', sa.Float(), nullable=True),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_competencia_academia_id'), ['academia_id'], unique=False)

    op.create_table('grados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('federacion', sa.String(length=10), nullable=True),
    sa.Column('dan_num', sa.Integer(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grados_academia_id'), ['academia_id'], unique=False)

    op.create_table('medallas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medallas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medallas_academia_id'), ['academia_id'], unique=False)

    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torneos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('organizador', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('precio_poomsae', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_combate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_ambas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_torneos_academia_id'), ['academia_id'], unique=False)

    op.create_table('banco_preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ABIERTA', name='bp_tipo'), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('puntaje_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dificultad', sa.SmallInteger(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantillas_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('modo_seleccion', sa.Enum('FIJA', 'ALEATORIA', name='pe_modo'), nullable=False),
    sa.Column('num_preguntas', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=10), nullable=False),
    sa.Column('total_competidores', sa.Integer(), nullable=False),
    sa.Column('acta_foto', sa.String(length=255), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_competencia.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultados_categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultados_categoria_academia_id'), ['academia_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_academia_id'), ['academia_id'], unique=False)

    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('numero_identidad', sa.String(length=20), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estatura', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('flexibilidad', sa.Enum('Baja', 'Media', 'Alta', name='flexibilidad_emun'), nullable=True),
    sa.Column('fecha_ultimo_grado', sa.Date(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumnos_academia_id'), ['academia_id'], unique=False)

    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('disciplina', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('sede', sa.String(length=120), nullable=True),
    sa.Column('grado_objetivo_id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('cupos', sa.Integer(), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ABIERTO', 'CERRADO', 'EN_EVALUACION', 'PENDIENTE_DECISION', 'PUBLICADO', 'ANULADO', name='ex_estado'), nullable=False),
    sa.Column('mostrar_resultado_al_alumno', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grado_objetivo_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_examen.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantilla_preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_examen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregunta_id'], ['banco_preguntas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plantilla_id', 'pregunta_id', name='uq_plantilla_pregunta')
    )
    op.create_table('pregunta_opciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['banco_preguntas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('ascensos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('grado_anterior_id', sa.Integer(), nullable=False),
    sa.Column('grado_nuevo_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.Enum('EXAMEN', 'MANUAL', name='as_origen'), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.ForeignKeyConstraint(['grado_anterior_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['grado_nuevo_id'], ['grados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=1), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'alumno_id', 'sucursal_id', name='uq_asistencia_fecha_alumno_sucursal')
    )
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asistencias_academia_id'), ['academia_id'], unique=False)
        batch_op.create_index('ix_asistencias_fecha_sucursal', ['fecha', 'sucursal_id'], unique=False)

    op.create_table('examen_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'FINALIZADO', name='ea_estado'), nullable=False),
    sa.Column('score_auto', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_manual', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('propuesta_resultado', sa.Enum('PROPUESTO_APROBADO', 'PROPUESTO_REPROBADO', name='ea_prop'), nullable=True),
    sa.Column('observacion_evaluadores', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id', 'alumno_id', name='uq_ea_examen_alumno')
    )
    op.create_table('examen_dictamen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('director_user_id', sa.Integer(), nullable=False),
    sa.Column('resultado_final', sa.Enum('APROBADO', 'REPROBADO', name='ed_res'), nullable=False),
    sa.Column('nota_final', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('observacion_final', sa.Text(), nullable=True),
    sa.Column('fecha_dictamen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['director_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id', 'alumno_id', name='uq_dictamen')
    )
    op.create_table('examen_evaluadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('PRINCIPAL', 'AUXILIAR', name='ee_rol'), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id', 'user_id', name='uq_ex_eval')
    )
    op.create_table('examen_inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('grado_actual_id', sa.Integer(), nullable=False),
    sa.Column('grado_objetivo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('INSCRITO', 'AUSENTE', 'EVALUADO', 'APROBADO', 'REPROBADO', 'PROMOVIDO', name='ei_estado'), nullable=False),
    sa.Column('nota_final', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('comentario_general', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grado_actual_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['grado_objetivo_id'], ['grados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id', 'alumno_id', name='uq_ex_alumno')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=30), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academia_id', 'alumno_id', 'anio', 'mes', name='uq_pago_tenant_alumno_anio_mes')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_academia_id'), ['academia_id'], unique=False)

    op.create_table('participaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=10), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('puntaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('medalla_id', sa.Integer(), nullable=True),
    sa.Column('valor_evento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pagado_evento', sa.Boolean(), nullable=False),
    sa.Column('fecha_pago_evento', sa.Date(), nullable=True),
    sa.Column('metodo_pago_evento', sa.String(length=30), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_competencia.id'], ),
    sa.ForeignKeyConstraint(['medalla_id'], ['medallas.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torneo_id', 'alumno_id', 'modalidad', name='uq_participaciones_torneo_alumno_modalidad')
    )
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participaciones_academia_id'), ['academia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_alumno_id'), ['alumno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_modalidad'), ['modalidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_torneo_id'), ['torneo_id'], unique=False)

    op.create_table('resultados_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resultado_categoria_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('nombre_competidor', sa.String(length=200), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('medalla_id', sa.Integer(), nullable=True),
    sa.Column('puntaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['medalla_id'], ['medallas.id'], ),
    sa.ForeignKeyConstraint(['resultado_categoria_id'], ['resultados_categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examen_alumno_preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_alumno_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_texto', sa.Text(), nullable=True),
    sa.Column('respuesta_opcion_id', sa.Integer(), nullable=True),
    sa.Column('es_correcta', sa.Boolean(), nullable=True),
    sa.Column('puntaje_asignado', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['examen_alumno_id'], ['examen_alumno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregunta_id'], ['banco_preguntas.id'], ),
    sa.ForeignKeyConstraint(['respuesta_opcion_id'], ['pregunta_opciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_alumno_id', 'pregunta_id', name='uq_eap_unica')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examen_alumno_preguntas')
    op.drop_table('resultados_detalle')
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participaciones_torneo_id'))
        batch_op.drop_index(batch_op.f('ix_participaciones_modalidad'))
        batch_op.drop_index(batch_op.f('ix_participaciones_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_participaciones_alumno_id'))
        batch_op.drop_index(batch_op.f('ix_participaciones_academia_id'))

    op.drop_table('participaciones')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_academia_id'))

    op.drop_table('pagos')
    op.drop_table('examen_inscripciones')
    op.drop_table('examen_evaluadores')
    op.drop_table('examen_dictamen')
    op.drop_table('examen_alumno')
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_index('ix_asistencias_fecha_sucursal')
        batch_op.drop_index(batch_op.f('ix_asistencias_academia_id'))

    op.drop_table('asistencias')
    op.drop_table('ascensos')
    op.drop_table('user_roles')
    op.drop_table('pregunta_opciones')
    op.drop_table('plantilla_preguntas')
    op.drop_table('examenes')
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_academia_id'))

    op.drop_table('alumnos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_academia_id'))

    op.drop_table('users')
    with op.batch_alter_table('resultados_categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultados_categoria_academia_id'))

    op.drop_table('resultados_categoria')
    op.drop_table('plantillas_examen')
    op.drop_table('banco_preguntas')
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_torneos_academia_id'))

    op.drop_table('torneos')
    op.drop_table('sucursales')
    with op.batch_alter_table('medallas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medallas_academia_id'))

    op.drop_table('medallas')
    with op.batch_alter_table('grados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grados_academia_id'))

    op.drop_table('grados')
    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_competencia_academia_id'))

    op.drop_table('categorias_competencia')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_academia_id'))

    op.drop_table('categorias')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_academia_id'))

    op.drop_table('auditoria')
    op.drop_table('roles')
    op.drop_table('academias')
    # ### end Alembic commands ###
