"""Agregar campos publicos a sucursales

Revision ID: dd31870b0a3f
Revises: c77ea32f331f
Create Date: 2026-03-03 18:25:30.779974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd31870b0a3f'
down_revision = 'c77ea32f331f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumen_publico', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_maps_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('foto_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_mensaje', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_sucursales_academia_id'), ['academia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sucursales_academia_id'))
        batch_op.drop_column('whatsapp_mensaje')
        batch_op.drop_column('whatsapp_numero')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('foto_3')
        batch_op.drop_column('foto_2')
        batch_op.drop_column('foto_1')
        batch_op.drop_column('google_maps_url')
        batch_op.drop_column('resumen_publico')

    # ### end Alembic commands ###
