"""Agregar notas practicas y pesos de examen

Revision ID: fed3f2b1ee7b
Revises: dd31870b0a3f
Create Date: 2026-03-06 11:22:31.535174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed3f2b1ee7b'
down_revision = 'dd31870b0a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen_inscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_teoria', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nota_poomsae', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nota_combate', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('observacion_poomsae', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observacion_combate', sa.Text(), nullable=True))

    with op.batch_alter_table('examenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usa_teoria', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('usa_poomsae', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('usa_combate', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('peso_teoria', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('peso_poomsae', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('peso_combate', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('nota_minima_aprobacion', sa.Numeric(precision=5, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examenes', schema=None) as batch_op:
        batch_op.drop_column('nota_minima_aprobacion')
        batch_op.drop_column('peso_combate')
        batch_op.drop_column('peso_poomsae')
        batch_op.drop_column('peso_teoria')
        batch_op.drop_column('usa_combate')
        batch_op.drop_column('usa_poomsae')
        batch_op.drop_column('usa_teoria')

    with op.batch_alter_table('examen_inscripciones', schema=None) as batch_op:
        batch_op.drop_column('observacion_combate')
        batch_op.drop_column('observacion_poomsae')
        batch_op.drop_column('nota_combate')
        batch_op.drop_column('nota_poomsae')
        batch_op.drop_column('nota_teoria')

    # ### end Alembic commands ###
